services:
  postgres:
    image: postgres:latest
    container_name: patient_project_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: patient_projectdb
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  patientproject.api:
    image: patient_project
    build:
      context: .
      dockerfile: PatientProject.Api/Dockerfile
    container_name: patient_project_webapi
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "13188:80"
  
volumes:
  postgres_data: